### ISSUE TITLE
Main Page Design

### ISSUE THREAD

**Issue by C4Framework** [C4Github/SiteDesign#1]
This needs to be done soon.

**Comment by jakemakes** [comment]
i've uploaded the first commit for a new design, check it out, i know the following haven't been addressed yet:

- i didn't make the logo yet
- i didn't think about the footer

**Comment by jakemakes** [comment]
i'm thinking about doing something like this: 
![screen shot 2014-12-04 at 3 18 10 pm](https://cloud.githubusercontent.com/assets/9539943/5709845/dc8ead7e-9a51-11e4-9c05-84d644f9afbe.png)

**Comment by jakemakes** [comment]
done.
